# Generated by Django 3.1.3 on 2020-11-08 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penpals',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=140)),
                ('password', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=25000)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='penpals.penpals')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='penpals.penpals')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='penpals.penpals')),
                ('id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='penpals.penpals')),
            ],
        ),
    ]
